riccio.riccio.*:
  type: config_entity
  label: 'Riccio configuration'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    options:
      type: mapping
      label: 'Options'
      mapping:
        itemSelector:
          type: string
          label: 'Item selector'
        popSelector:
          type: string
          label: 'Pop selector'
        perRow:
          type: integer
          label: 'Items per row'
        mediaQueries:
          type: text
          label: 'Media queries list'

field.formatter.settings.entity_reference_riccio:
  type: mapping
  label: 'Entity reference Riccio'
  mapping:
    riccio_options:
      type: string
      label: 'Riccio options'